#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H

#define BTM_DEF_LOCAL_NAME   "BLU Bold N2"

#define BLE_VND_INCLUDED   TRUE

#define BTA_HOST_INTERLEAVE_SEARCH TRUE

#define BT_CLEAN_TURN_ON_DISABLED TRUE

#endif